### ISSUE TITLE
Create wrappers for OS functions

### ISSUE THREAD

**Issue by ClarkPoon** [lhr-solar/BPS#401]
The code is set up so we have to call `assertOSError` after each OS function to check for errors. We are also not ever changing some of the parameters for the OS functions. It would be nice if we had a wrapper so we could do something like
```C
SemPost(&Fault_Sem4);
```
instead of
```C
OSSemPost(&Fault_Sem4,
                        OS_OPT_POST_1,
                        &err);
assertOSError(err);
```

This would make the code more readable and make it so we are less likely to forget the call to `assertOSError`, since it will be inside the wrapper.

**Comment by manthanand** [comment]
This issue is now going to be expanded to be wrappers for OS functions for portability. For example, we will have a ``BPS_RTOS`` library that will include ``BPS_RTOS`` functions such as ``BPS_RTOSSemPend()``. These functions will include all OS related functions such as ``OSSemPend()`` & ``assertOSError()``.  This will make it easier to move from different OS's.
